package com.pvnetwork.desktop

data class ShellCopy(
    val profiles: String,
    val noProfiles: String,
    val connection: String,
    val diagnostics: String,
    val noDiagnostics: String,
    val language: String,
    val themeIcon: String,
    val protocol: String,
    val endpoint: String,
    val addProfiles: String,
    val addProfilesHint: String,
    val addProfile: String,
    val close: String,
    val delete: String,
    val connect: String,
    val disconnect: String,
    val subscriptions: String,
    val testAll: String,
    val manual: String,
    val latencyTimeout: String,
    val importedCount: String,
    val importFailed: String,
    val stateDisconnected: String,
    val statePreparing: String,
    val stateConnecting: String,
    val stateConnected: String,
    val stateDisconnecting: String,
    val stateError: String,
    val coreReady: String,
    val coreMissingShort: String,
    val storageUnavailable: String,
    val colName: String,
    val colProtocol: String,
    val colEndpoint: String,
    val colSource: String,
    val colLatency: String,
    val colActions: String,
    val profilesCount: String,
    val subName: String,
    val subUrl: String,
    val subAdd: String,
    val subAdded: String,
    val subsEmpty: String,
    val subNeverUpdated: String,
    val subUpdate: String,
    val subUpdated: String,
    val subRemoved: String,
    val subUpdateAll: String,
    val subsUpdatedAll: String,
)

fun shellCopy(language: AppLanguage): ShellCopy = when (language) {
    AppLanguage.PERSIAN -> ShellCopy(
        profiles = "سرورها",
        noProfiles = "سروری نیست — از دکمه «افزودن پروفایل» لینک بچسبانید یا اشتراک اضافه کنید",
        connection = "وضعیت اتصال",
        diagnostics = "گزارش فنی",
        noDiagnostics = "رویداد تشخیصی وجود ندارد",
        language = "زبان",
        themeIcon = "پوسته",
        protocol = "پروتکل",
        endpoint = "آدرس",
        addProfiles = "افزودن پروفایل",
        addProfilesHint = "یک یا چند لینک (هر خط یک لینک) از نوع vless / vmess / trojan / ss را اینجا بچسبانید",
        addProfile = "افزودن",
        close = "بستن",
        delete = "حذف",
        connect = "اتصال",
        disconnect = "قطع اتصال",
        subscriptions = "اشتراک‌ها",
        testAll = "تست تأخیر همه",
        manual = "دستی",
        latencyTimeout = "بی‌پاسخ",
        importedCount = "{n} پروفایل اضافه شد (خطای {f} خط)",
        importFailed = "ناموفق",
        stateDisconnected = "قطع است",
        statePreparing = "در حال آماده‌سازی…",
        stateConnecting = "در حال برقراری…",
        stateConnected = "متصل",
        stateDisconnecting = "در حال قطع…",
        stateError = "خطا",
        coreReady = "هسته {version}",
        coreMissingShort = "هسته Xray پیدا نشد",
        storageUnavailable = "ذخیره‌سازی محلی مقداردهی نشد",
        colName = "نام",
        colProtocol = "پروتکل",
        colEndpoint = "آدرس سرور",
        colSource = "منبع",
        colLatency = "تأخیر",
        colActions = "",
        profilesCount = "{n} سرور · {s} اشتراک",
        subName = "نام",
        subUrl = "لینک اشتراک (http)",
        subAdd = "افزودن اشتراک",
        subAdded = "اشتراک اضافه شد: {n} سرور",
        subsEmpty = "هنوز اشتراکی اضافه نشده — لینک اشتراک PVNetwork یا هر سرویس‌دهنده را بالا وارد کنید",
        subNeverUpdated = "به‌روز نشده",
        subUpdate = "به‌روزرسانی",
        subUpdated = "به‌روز شد: {n} سرور",
        subRemoved = "اشتراک و سرورهایش حذف شد",
        subUpdateAll = "به‌روزرسانی همه",
        subsUpdatedAll = "{n} از {t} اشتراک به‌روز شد",
    )

    AppLanguage.ENGLISH -> ShellCopy(
        profiles = "Servers",
        noProfiles = "No servers yet — add links with \"Add profile\" or add a subscription",
        connection = "Connection",
        diagnostics = "Diagnostics",
        noDiagnostics = "No diagnostic events",
        language = "Language",
        themeIcon = "Theme",
        protocol = "Protocol",
        endpoint = "Endpoint",
        addProfiles = "Add profile",
        addProfilesHint = "Paste one or more share links (one per line): vless / vmess / trojan / ss",
        addProfile = "Add",
        close = "Close",
        delete = "Delete",
        connect = "Connect",
        disconnect = "Disconnect",
        subscriptions = "Subscriptions",
        testAll = "Test all latency",
        manual = "manual",
        latencyTimeout = "timeout",
        importedCount = "{n} profiles added ({f} failed lines)",
        importFailed = "Failed",
        stateDisconnected = "Disconnected",
        statePreparing = "Preparing…",
        stateConnecting = "Connecting…",
        stateConnected = "Connected",
        stateDisconnecting = "Disconnecting…",
        stateError = "Error",
        coreReady = "core {version}",
        coreMissingShort = "Xray core not found",
        storageUnavailable = "Local storage could not be initialized",
        colName = "Name",
        colProtocol = "Protocol",
        colEndpoint = "Server",
        colSource = "Source",
        colLatency = "Latency",
        colActions = "",
        profilesCount = "{n} servers · {s} subscriptions",
        subName = "Name",
        subUrl = "Subscription URL (http)",
        subAdd = "Add subscription",
        subAdded = "subscription added: {n} servers",
        subsEmpty = "No subscriptions yet — paste your PVNetwork or provider subscription URL above",
        subNeverUpdated = "never updated",
        subUpdate = "Update",
        subUpdated = "updated: {n} servers",
        subRemoved = "subscription and its servers removed",
        subUpdateAll = "Update all",
        subsUpdatedAll = "{n} of {t} subscriptions updated",
    )
}
